### PR TITLE
Fix possible double service reference in channel list to import.

### PR DESCRIPTION
**Pull request by pr2git**
Add a long description for the EPGimport parameters.
For skinners the widget description must be added, to EPGImportConfig screen name:
Example:
In:

<screen name="EPGImportConfig" position="fill" title="EPG Import Configuration" flags="wfNoBorder">

Add:
<widget name="description" position="30,570" size="720,300" itemHeight="38" font="Regular;30" valign="top"/>

### CODE REVIEW

**Comment by WanWizard** [comment]
What is the relation between "Fix possible double service reference in channel list to import" and "Add a long description for the EPGimport parameters"?

**Comment by pr2git** [comment]
None it is just a patch that include both. The avoid duplicate is just 1 line of code added.

**Comment by pr2git** [comment]
Check the line added in EPGConfig.py 1 comment 1 code line.

**Comment by pr2git** [comment]
Will this change be accepted or not?

**Pull request merged**
