### PR TITLE
Add option "Repeat import once through"

### PR DESCRIPTION
**Pull request by Dima73**
-Repeat the import once through x hours (1 - 23, 0 - disabled) in this session only.
more info

https://forums.openpli.org/topic/96230-epgimporter-added-the-ability-to-download-epg-data-cyclically-at-a-set-hourly-interval/ -cosmetics import  and variable names

### CODE REVIEW

**Comment by littlesat** [comment]
Actually I do not like this idea at all as it will load the epg servers (we also support) extra... the resources need to come from somewhere... As far I can see it reads everything at the specific interval and then it will load the servers more and more.
When it does load all at each interval I hope other images will also not do this... it will ask for more data from the services which makes them also more expensive.

**Comment by Dima73** [comment]
Not.
Patch logic
auto start 17:00 -->run
+
start once repeat timer
+
start new auto start timer for next day

**Comment by littlesat** [comment]
Why do you need 17.00,
One repeat and then each 24 hours. What added value do you want to try to get here? Then better keep somewhere the last time it is synchronized and when this is >24 hours ago then download right away.... then each 24 hours. Also a fixed time 17.00 is not 'smart' in regards to server load...

**Comment by Dima73** [comment]
start new auto start timer for next day(e.g. 17:00)
+
start once repeat timer
+
start new auto start timer for next day

And so every day one additional import

**Comment by littlesat** [comment]
The commit also has two parts... as the plugin was it imports enigma... and now what is needed from enigma is imported.... so there are (at least) two different things in the commit.

**Comment by Dima73** [comment]
Yes.
`-cosmetics import  and variable names`
At the same time, I rewrote the names of the variables, corrected the import into E2 and added additional checks.
It was a lot of work.
That's how it happened.

**Comment by adrianmihalko** [comment]
Instead of this a proper  crontab support (including run this tool manually from cli) would be 100 better.

**Comment by WanWizard** [comment]
> Instead of this a proper crontab support (including run this tool manually from cli) would be 100 better.

For the few technical savvy users perhaps, but 99.99% would have no clue what a crontab is.

**Pull request merged**
