### PR TITLE
xmltvconverter: use six to handle both python2,3

### PR DESCRIPTION
**Pull request by athoik**
Use six.ensure_str to handle python2 with encode utf-8 and python3
that is always utf-8.

### CODE REVIEW

**Comment by nautilus7** [comment]
@WanWizard @athoik any reason why this hasn't been merged yet? Thanks.

**Comment by athoik** [comment]
If we don't want to use it, due to six we can use something like " if sys.major >= 3 else "

**Comment by WanWizard** [comment]
I didn't know it was open, it wasn't in my todo list.

I have no objections, six is used in lots of other places too.

**Comment by nautilus7** [comment]
@WanWizard so are you going to merge? @athoik doesn't have access here to do it on his own, I think.

Regards

**Comment by athoik** [comment]
That is correct, i don't have access. 

Take your time and merge it whenever possible.

**Comment by WanWizard** [comment]
Sorry, forgot.

**Comment by nautilus7** [comment]
No problem, thank you.

**Pull request merged**
