### PR TITLE
Cosmetic change

### PR DESCRIPTION
**Pull request by AbuBaniaz**
One liners that are preferred by some

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
These are the one line layout that Littlesat prefers. No functional change.

Please `squash and merge`, not just `merge` so that the commit log does not show two commits

**Comment by AbuBaniaz** [comment]
Thanks to @Iansav

**Comment by WanWizard** [comment]
May I say that I found the original 1000 times better? 

I absolutely loath one liners, code is meant to be read by humans, computers don't give a toss about formatting...

**Comment by IanSav** [comment]
I understand the desire for readability but the code should be correct for PEP8 as well.  The original was laid out well for human readability but was not fully correct.  I made the changes that Abu requested and I am okay with the change.

My preference would be to have a single version of the code that everyone agrees to share.  ;)

**Pull request merged**
