### PR TITLE
Rename custom.channels.xml.txt to custom.channels.xml

### PR DESCRIPTION
**Pull request by jeepcook**

### CODE REVIEW

**Comment by WanWizard** [comment]
@pr2git any particular reason they were called ".txt" ?

**Comment by pr2git** [comment]
I create them with the .txt extension because I just fear that if EPGImport is update later on with new improvements, the file will be overwritten by the opkg update process. So end-user will lost all its setup.
Moreover this is an explanation file which we have dummy entries as exemple, so making it live is a total non-sense.
Here is it current content:



<?xml version="1.0" encoding="latin-1"?>
<channels>
	<channel id="MyChannel1.uk">4097:0:1:BA08:3:0:0:0:0:0:http%3a//dummy.com/</channel> 
	<channel id="MyChannel2.fr">5001:0:1:A315:3:0:0:0:0:0:http%3a//dummy.com/</channel> 
</channels>

There is no reason to make it live. Please keep it as .txt as exemple file.

**Comment by jeepcook** [comment]
> 
> 
> I create them with the .txt extension because I just fear that if EPGImport is update later on with new improvements, the file will be overwritten by the opkg update process. So end-user will lost all its setup.
> Moreover this is an explanation file which we have dummy entries as exemple, so making it live is a total non-sense.
> Here is it current content:
> 4097:0:1:BA08:3:0:0:0:0:0:http%3a//dummy.com/ 5001:0:1:A315:3:0:0:0:0:0:http%3a//dummy.com/
> 
> There is no reason to make it live. Please keep it as .txt as exemple file.

Ok sorry pr2, I didn't understand that. But it's confusing. A readme extension or other will be better, no?

**Comment by jeepcook** [comment]
abandoned

**Pull request closed without merging**
