### PR TITLE
Run from main menu

### PR DESCRIPTION
**Pull request by AbuBaniaz**
Reword the function that allows to import from main menu

### CODE REVIEW

**Comment by WanWizard** [comment]
What do you mean by "now"? Shouldn't it just be:
````
show EPG Import in extensions
show EPG Import in main menu
````
?

**Comment by AbuBaniaz** [comment]
As mentioned in the other abandoned pull request, there is confusion of functions and process.

Based on old wording
Show EPG import in main menu = Show the function to fetch epg in the main menu. This is the executer/doer/processor
Show EPG Import in extensions = Show the plugin config in extensions menu

I have re-worded the function to fetch epg from the main menu to avoid confusion of what is being added to the main menu  as well as to clarify things for the next person who looks at this code. The "now" bit was taken from the wording used by epg refresh.

As a side note, I think it would have been better to have the executer/doer/processor in extensions list, not the plugin config.

epg now

**Comment by WanWizard** [comment]
I think it is this that confuses me, because afaik the plugin doesn't have an "import now" function, you need to start the plugin and press the yellow button to start a manual import? 

Or have I missed more? ;-)

**Comment by AbuBaniaz** [comment]
The plugin has that option. Maybe you have not enabled it because you though it was a plugin. Please try the option in the current coding. I hope you agree that my wording makes it clearer.

I am in two minds whether `EPG Import now` or `EPG Importer now` is better.

**Comment by WanWizard** [comment]
Never knew that, learning all the time!

I'd say "EPG import now" is better, as that is the action you want to perform. You can't say "I am going to importer now"...

**Pull request merged**
